### ISSUE TITLE
Is this package deprecated in favor of  juju/errors ? 

### ISSUE THREAD

**Issue by allan-simon** [juju/errgo#12]
https://github.com/juju/errors ?

If so can the readme be modified to reflect that ?

**Comment by urosj** [comment]
No, there are two "error" packages being used. Juju core uses juju/errors, while some external services around juju use errgo. For any contribution to juju, juju/errors is preferred.

**Comment by allan-simon** [comment]
thanks for your quick answer,  hmm does it mean  errgo is still here for the only reason of "it's still used by other projects"  ? But as for a new project, is there any reason why one would choose errgo instead of choosing errors ?

**Comment by howbazaar** [comment]
Both juju/errors and juju/errgo were created to be able to annotate errors with file and line locations in order to provide extra context to errors.

They differed in their general approach to wrapping and the names of the various functions.  juju/errgo and juju/errors will happily work together as they share a common definition of the interface around the file/line stack.  My suggestion is to use the library that makes more sense to you.
