### ISSUE TITLE
mask hides errors case by default

### ISSUE THREAD

**Issue by xh3b4sd** [juju/errgo#8]
Hey there,

we really like that library and use it in several projects. Currently I try to wrap my head around the original cause of an error. I noticed that one needs to do something like `errgo.Mask(err, errgo.Any)` to be able to do something like `errgo.Cause(err)`, to find the original cause of a problem. I question myself why one ever would like to hide the cause of an err. Wouldn't it be nicer to track the cause of each error by default or provide something like `MaskWithCause(error)`? May someone could explain the intentions behind that behaviour or if I miss something obvious. 

All the best

**Comment by klauspost** [comment]
I recently ran into the same issue, and I was actually very surprised that I couldn't find the original cause of the error once it had been masked.

I tried adding this "else" statement to the "NoteMask" function, which sets that cause to the overlaying cause, or sets it to the underlying error itself. This will make the cause propagate upwards:

```
    if len(pass) > 0 {
        if cause := Cause(underlying); match(cause, pass...) {
            newErr.Cause_ = cause
        }
    } else {
        cause := Cause(underlying)
        newErr.Cause_ = cause
    }
```

This will however be incompatible with the current library. A solution could be to add another function call, that returns the top-most error, so "empty" masks can be used. I will send a pull-request with that.

**Comment by rogpeppe** [comment]
I'm glad you like the library, and thanks for the feedback.

This behaviour is deliberate. See https://rogpeppe.wordpress.com/2014/04/23/some-suggested-rules-for-generating-good-errors-in-go/ for the rationale behind it.

To summarise, always preserving the cause of the error makes for fragile programs because if you change some implementation, you can rarely be certain that no caller is relying on some cause returned by a function call made by the old implementation but not the new.

In my view, the set of possible error causes should be part of the contract of the function and documented as such. errgo is designed to facilitate that, and to make it harder to
have accidentally clashing cause semantics (for example, an ErrNotFound can mean very
different things depending on what returns it).

BTW the canonical import path for this package is now gopkg.in/errgo.v1

**Comment by rogpeppe** [comment]
See also https://github.com/juju/errgo/issues/9

**Comment by klauspost** [comment]
@rogpeppe - thanks for the explanation. I am aware of the pros and cons of "passing the buck". 

However, there are other ways of keeping tracks of these implementation details, and I feel it is a bit restrictive for a library to hide information from me, and I think the PR nicely addresses this, by adding a separate function for retrieving the "top" error.

**Comment by rogpeppe** [comment]
If you always want to maintain the top error, then you can always
pass errgo.Any to Mask.

I'd be interested to see an example of where you find this too restrictive.
My experience that the code that results is more transparent because
of the explicitness, and I haven't found any places where it has
actually been a problem.

**Comment by rogpeppe** [comment]
Working as intended.
